### ISSUE TITLE
Change gif provider

### ISSUE THREAD

**Issue by leovarmak** [maxpert/raspchat#14]
Hey !

Its better if we change the gif provider as some of the pictures aren't accurate as well contain disturbing content for users. You could probably try this [Popkey](http://popkey.co/) ?

**Comment by caioalonso** [comment]
Is this still valid? I could give it a try.

**Comment by leovarmak** [comment]
Hey,

I got a mail that Raspchat is being rewritten in Node. Get get a chance to check if the new version is live as I am out. 
But the old thing had issues. The GIFs werent moderated I guess.

**Comment by maxpert** [comment]
We would probably move totally away from gifs on server to gifs from client using giphy. Closing this issue since it will be irrelevant.
