### ISSUE TITLE
spacing issue between input and chat

### ISSUE THREAD

**Issue by rileytg** [maxpert/raspchat#17]
<img width="537" alt="raspchat_and_keyboard" src="https://user-images.githubusercontent.com/692817/33184190-4aa1985a-d030-11e7-8d56-68fabdfd0fb5.png">

**Comment by rileytg** [comment]
chrome, osx (latest)
http://raspchat.com/static/chat.html

**Comment by maxpert** [comment]
Seems like a minor CSS issue. Feel free to send PR.

**Comment by maxpert** [comment]
Has been fixed in latest checkin `ad338373221d7c5057fc63bd639bac10731bbc83`
