### ISSUE TITLE
Previously changed nicks become undefined

### ISSUE THREAD

**Issue by wybiral** [maxpert/raspchat#18]
If you join the chat as a previous nickname the line `foo changed nick to bar` becomes `foo changed nick to undefined`.

Steps to reproduce:
1. Join chat
2. Change nick
3. Exit chat
4. Rejoin chat as previous nick

**Comment by maxpert** [comment]
Has been fixed in latest commit `d63f20224f52fb705eab8f05e7b2733142dcdc4e`
