### ISSUE TITLE
[SECURITY] RaspChat Website Demo

### ISSUE THREAD

**Issue by ForgivenNin** [maxpert/raspchat#21]
_@maxpert I am completely new to this repo (possibly even a passerby), so please forgive me if this issue does not comply with any contribution guidelines, as I find this quite urgent._

**On your demo page, where you can test out the chat server, it appears that someone or something is spamming the "user login" with a numerous amount of names.**
You can tell because the format of the names always contains a hyphen in the middle.

**Comment by maxpert** [comment]
Thank for reporting this. I don't think I will bring up the demo for now. Requires both money and time to keep it hosted and running. People interested can download and run it pretty quickly. Plus with image sharing option I don't want to end up in a any pronography mess problem.
